# Generated by Django 5.2.8 on 2025-11-19 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("serving_size", models.CharField(default="100g", max_length=50)),
                (
                    "calories",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "protein_g",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "carbs_g",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "fats_g",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("fiber_g", models.FloatField(blank=True, null=True)),
                ("sugar_g", models.FloatField(blank=True, null=True)),
                ("sodium_mg", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_g",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nutrition.food"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("instructions", models.TextField()),
                ("ingredients_data", models.JSONField()),
                ("total_calories", models.FloatField()),
                ("total_protein_g", models.FloatField()),
                ("total_carbs_g", models.FloatField()),
                ("total_fats_g", models.FloatField()),
                ("prep_time_minutes", models.IntegerField(blank=True, null=True)),
                ("servings", models.IntegerField(default=1)),
                ("is_ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_g", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("carbs_g", models.FloatField()),
                ("fats_g", models.FloatField()),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("meal_date", models.DateField()),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nutrition.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-meal_date", "-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(50)]
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(20)]
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "Sedentary (little/no exercise)"),
                            (1.375, "Light (1-3 days/week)"),
                            (1.55, "Moderate (3-5 days/week)"),
                            (1.725, "Active (6-7 days/week)"),
                            (1.9, "Very Active (athlete)"),
                        ],
                        default=1.2,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("maintain", "Maintain Weight"),
                            ("lose", "Lose Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        default="maintain",
                        max_length=10,
                    ),
                ),
                ("bmr", models.FloatField(default=0)),
                ("tdee", models.FloatField(default=0)),
                ("target_calories", models.FloatField(default=0)),
                (
                    "protein_ratio",
                    models.FloatField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "carbs_ratio",
                    models.FloatField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fats_ratio",
                    models.FloatField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_calories", models.FloatField(default=0)),
                ("total_protein_g", models.FloatField(default=0)),
                ("total_carbs_g", models.FloatField(default=0)),
                ("total_fats_g", models.FloatField(default=0)),
                ("target_calories", models.FloatField()),
                ("target_protein_g", models.FloatField()),
                ("target_carbs_g", models.FloatField()),
                ("target_fats_g", models.FloatField()),
                ("meals_logged", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
